apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
spec:
  project: default
  source:
    repoURL: https://github.com/amit-o/argocd-example-apps.git
    targetRevision: HEAD
    path: apps-of-apps
  destination:
    server: https://kubernetes.default.svc
    namespace: default