apiVersion: platform.coralogix.com/v1alpha1
kind: ArgoJob
metadata:
  name: pi
spec:
  suspend: false
  template:
    template:
      spec:
        containers:
        - name: pi
          image: perl:5.34.0
          command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
        restartPolicy: Never
    backoffLimit: 4
