apiVersion: platform.coralogix.com/v1alpha1
kind: ArgoJob
metadata:
  name: pi
spec:
  suspend: false
  template:
    template:
      spec:
        containers:
        - name: pi
          image: perl:5.34.0
          command: ["exit",  "1"]
        restartPolicy: Never
    backoffLimit: 4
